version: '3.8'

services:
  vrp-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://103.226.248.168:5432/vrp_ai?currentSchema=dev3year
      - USERNAME=vrp_ai
      - PASSWORD=vrp
