server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://103.82.132.72:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect